Feature/backend 17
KenyaMasuko/qin-app-team-a pull request #5
Opened 2023-04-30 10:33 UTC by kotu-kotuo

## Notion URLとテスト環境URL

[- https://example.com](https://www.notion.so/ddb9768ff69b4f36b2192f9cdb6f98a2?v=95db7050e3a9456ab29330becc7ad7c1&p=cb611d7b4396446185f0d3ab2a76cba1&pm=s)

## やったこと

- FastAPI導入
- ChatGPTの連携
- Unsplashの画像表示
- キーワードでレシピ提案
- レシピの詳細を生成、表示

## その他

- テスト環境URLの用意の仕方がわからなかったです
- vercelでデプロイ失敗してるみたいです（ローカル環境ではbuild成功しているのですが

2023-05-04 14:01 UTC, makkenno requested changes
お伝え忘れていましたが、pythonライブラリのパッケージのバージョンを開発者で共有するためにrequirements.txtを作成していただけると嬉しいです！
pip freeze > requirements.txtとbackendディレクト内でコマンドを打っていただくと作成できます！
よろしくお願いします！

2023-05-04 14:01 UTC, makkenno commented on node_modules/.yarn-integrity
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) こちらのディレクトリは削除でお願いします！

2023-05-04 14:01 UTC, makkenno commented on backend/main.py
> +        print("1")
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) こちらawaitの並列化の実装はいかがでしたか？技術的な問題で実装不可能でしょうか？

2023-05-07 04:54 UTC, kotu-kotuo commented on backend/main.py
> +        print("1")
並列化の実装は、もともとmax_tokens=1000にするとエラーが出ることへの対処として案が出されたもので、
tokensのエラーはSWRの使用をやめたら解消しているので（ちなみに並列化の処理は試してみましたがエラー解消しませんでした...）、今現在、実装する優先度は低いかと思いまして、実装しませんでした。
また必要になりましたら、実装します！

2023-05-07 05:36 UTC, kotu-kotuo commented on node_modules/.yarn-integrity
削除できました！

2023-05-08 11:07 UTC, merged