Feature/frontend 07
KenyaMasuko/qin-app-team-a pull request #6
Opened 2023-05-09 03:44 UTC by t5a1r1ou

## Notion URLとテスト環境URL

- https://www.notion.so/UI-7530e6007ead44e0b25d32f18d34435d

## やったこと

- 選択肢UI作成
- 選択肢UIのグループ作成

## その他

- やり方として適切かわからないですが、グループのpropsに選択肢押下時のロジックを入れられるようにしています。
- MantineのGroupコンポーネントでgapを縦横分けて設定するのができなかったので、styleで直接書いてますが、より良い方法があればアドバイスいただきたいです。

2023-05-09 03:46 UTC, t5a1r1ou commented
すみません、vercelのログが見れないので、ビルドこけたままです。

2023-05-10 22:06 UTC, KenyaMasuko requested changes
レビューしました！logの有無の箇所以外は任意で対応お願いします🙏
ビルドが失敗してしまうのは frontendディレクトリにある `pnpm-lock.yml`が原因っぽいので（バックエンドの開発の際に使用したもの？）お手数ですがこのPRで一緒に削除してもらえると嬉しいです！

2023-05-10 22:06 UTC, KenyaMasuko commented on frontend/src/component/ToggleOptionGroup/ToggleOptionGroup.tsx
> +      </Group>
ここの箇所のgapを使用してる箇所ですが、大きな問題を特に感じないので全然このままでも問題ないかと思います！
他に同じようなことを実現するとしたら [Gridコンポーネント](https://mantine.dev/core/grid/)を使用するとかですかね〜

```ts
<Grid ref={ref} gutter="xs">
  {children.map((child) => (
    <Grid.Col key={child} span="content">
      <ToggleOption
        value={child}
        onClick={() => {
          onClickOption(child);
         }}
       >
          {child}
        </ToggleOption>
     </Grid.Col>
  ))}
</Grid>
```

こんな感じになるかと思います！もし興味があれば試してみてください笑（現状のコードでも問題ないと思います！）

2023-05-10 22:06 UTC, KenyaMasuko commented on frontend/src/component/ToggleOptionGroup/ToggleOptionGroup.tsx
> +    { children, onClickOption = (child) => console.log(child), ...others },
Arrow Functionの部分（ `(child) => console.log(child)` ）で、現状のコードでも問題はないのですが、現状のArrow Functionの書き方ですと何かをreturnする時の書き方なので、返り値がvoidなら
`(child) => { console.log(child) } )`にした方がいいかもです！（あとでログを消す用のコメントなんかも付け加えておいてもらうかlogも削除していただけると...🙏）

2023-05-10 22:06 UTC, KenyaMasuko commented on frontend/src/component/ToggleOptionGroup/ToggleOptionGroup.tsx
> +            onClick={() => onClickOption(child)}
この箇所も `onClick={() => { onClickOption(child) } }`が望ましいですね！

2023-05-11 12:29 UTC, t5a1r1ou commented on frontend/src/component/ToggleOptionGroup/ToggleOptionGroup.tsx
> +      </Group>
縦の間隔と横の間隔を変える方法わからなかったので、一旦そのままプッシュしてます。。！

2023-05-11 12:29 UTC, t5a1r1ou commented on frontend/src/component/ToggleOptionGroup/ToggleOptionGroup.tsx
> +    { children, onClickOption = (child) => console.log(child), ...others },
確かに、、！今まであんま意識してなかったです！ありがとうございます！

2023-05-11 22:10 UTC, KenyaMasuko commented on frontend/src/component/ToggleOptionGroup/ToggleOptionGroup.tsx
> +      </Group>
僕も横縦を個別で調整する方法がわからないのでこのまま行きましょうw

2023-05-11 22:14 UTC, KenyaMasuko commented
修正ありがとうございます！良さげです！
![LGTM](https://image.lgtmoon.dev/137097)

2023-05-11 22:14 UTC, merged